model: 
    modules:
        tacotron:
            input_adaptor: model.adaptor.espnet_tacotron2:espnetTacotron2Adaptor
            model_class: espnet.nets.pytorch_backend.e2e_tts_tacotron2:Tacotron2
            config_file: conf/espnet/tts/train_pytorch_tacotron2.yaml
            freeze: False
            output: ['generate_speech']

dataset:
    features: ['tokenid.list', 'fbank#wav.scp', 'resemblyzer#wav.scp']
    collate_fn: 'pad_to_max'
    # only support batch_size: 1
    batch_size: 1
    fs: 16000


# multiple_optimizer
optimizer:
    type: 'Adam'
    conf:
        lr: 0.0001

trainer:
    iteration_type: 'iterations'
    iterations: 100000
    save_per_iterations: 10000
    eval_per_iterations: 100
    accum_grad: 1

logger:
    log_metrics: False
    save: ['scp#generate_speech']
    #logger_conf: conf/svsnet_logger_svs20.yaml
    #save: ['utt_score.txt#utt_score']
