model: model.MOSNet:MOSNet
net:
    # multiple_optimizer
    conv_encoder:
        layers: 12
        channel: [16, 16, 16, 32, 32, 32, 64, 64, 128, 128, 128]
        activations: ['relu', 'relu', 'relu', 'relu', 'relu', 'relu', 'relu', 'relu', 'relu', 'relu', 'relu', 'relu']
        kernel: [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]
        stride: [3, 1, 3, 1, 1, 3, 1, 1, 3, 1, 1, 3]
    
    lstm_encoder:
        layers: 1
        hidden_size: [128]
        bidirectional: [True]
    
    decoder:
        layers: 2
        hidden_size: [128, 1]
        activations: ['relu', '']
        dropout: [0, 0]
    
    criterion:
        type: 'MSE'
        frame: True


dataset:
    feature: ['spectrogram', 'score.txt']
    label: ['score.txt']
    exclude_inference: ['score.txt']
    collate_fn: 'pad_to_max'
    batch_size: 64

# multiple_optimizer
optimizer:
    type: 'Adam'
    conf:
        lr: 0.001

trainer:
    iteration_type: 'epoch'
    iterations: 500
    save_per_iterations: 10
    eval_per_iterations: 1
    accum_grad: 1
