model: model.SVSNet.SVSNet:regression_model

dataset:
    features: ['spectrogram#wav.scp', 'spectrogram#wav1.scp', 'score.txt']
    label: ['score.txt']
    collate_fn: 'pad_to_max'
    batch_size: 64
    fs: 16000


# multiple_optimizer
optimizer:
    type: 'Adam'
    conf:
        lr: 0.0001

trainer:
    iteration_type: 'epoch'
    iterations: 30
    save_per_iterations: 10
    eval_per_iterations: 1
    accum_grad: 1

test_logger: model.SVSNet.metric:SVSNet_metric
tester:
    metric: sys_no_mse # sys_no_mse, sys, all_no_mse, all
    metric_type: mean_utt
    dataset: VCC18

